# Generated by Django 5.1.3 on 2024-11-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва відділу"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "room_number",
                    models.PositiveIntegerField(verbose_name="Номер кімнати"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Назва посади")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Оклад"
                    ),
                ),
                (
                    "bonus_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Відсоток премії"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва проекту"),
                ),
                ("deadline", models.DateField(verbose_name="Термін виконання")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Бюджет"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Ім'я")),
                ("last_name", models.CharField(max_length=50, verbose_name="Прізвище")),
                (
                    "middle_name",
                    models.CharField(max_length=50, verbose_name="По батькові"),
                ),
                ("address", models.TextField(verbose_name="Адреса")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("Special", "Спеціальна"),
                            ("Secondary", "Середня"),
                            ("Higher", "Вища"),
                        ],
                        max_length=20,
                        verbose_name="Освіта",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.department",
                        verbose_name="Відділ",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.position",
                        verbose_name="Посада",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата початку")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.department",
                        verbose_name="Відділ",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
        ),
    ]
